# Build cno + ext-oxc and collect everything into dist\exe\
$ErrorActionPreference = "Stop"

$BuildDir    = "build"
$OxcBuildDir = "ext-oxc\build"
$DistDir     = "dist\exe"
$Root        = $PSScriptRoot

# ── 1. Main project ───────────────────────────────────────────────────────────
cmake -S . -B $BuildDir -DCMAKE_BUILD_TYPE=Release
cmake --build $BuildDir --config Release --parallel

# ── 2. ext-oxc ────────────────────────────────────────────────────────────────
# cno.lib is generated by MSVC alongside the exe
$CnoLib = "$Root\$BuildDir\circu.js\Release\cjs.lib"
if (-not (Test-Path $CnoLib)) {
    # Debug build fallback
    $CnoLib = "$Root\$BuildDir\circu.js\Debug\cjs.lib"
}
if (-not (Test-Path $CnoLib)) {
    throw "Could not find cjs.lib under $BuildDir\circu.js\. Build the main project first."
}

cmake -S ext-oxc -B $OxcBuildDir -DCMAKE_BUILD_TYPE=Release `
  -DCJS_DIR="$Root\circu.js" `
  -DCNO_IMPLIB="$CnoLib"
cmake --build $OxcBuildDir --config Release --parallel

# ── 3. Collect into dist\exe\ ─────────────────────────────────────────────────
New-Item -ItemType Directory -Force -Path "$DistDir\ext" | Out-Null

Copy-Item "$BuildDir\stage\cno.exe" "$DistDir\cno.exe" -Force
Copy-Item "$BuildDir\stage\qjs.dll" "$DistDir\qjs.dll" -Force

# oxc.dll can land in Release\ or directly in build dir depending on generator
$OxcDll = @(
    "$OxcBuildDir\Release\oxc.dll",
    "$OxcBuildDir\oxc.dll"
) | Where-Object { Test-Path $_ } | Select-Object -First 1

if ($OxcDll) {
    Copy-Item $OxcDll "$DistDir\ext\oxc.dll" -Force
} else {
    Write-Warning "oxc.dll not found — ext-oxc may have failed to build"
}

Write-Host ""
Write-Host "dist\exe\ contents:"
Get-ChildItem "$DistDir", "$DistDir\ext" | Format-Table Name, Length
