import { deepStrictEqual, ok, strictEqual, throws } from 'node:assert';
import * as crypto from 'node:crypto';

// generateKeyPairSync for the RFC 8410 algorithms (X25519, X448, Ed25519,
// Ed448). Import for these types already worked; only generation was gated, and
// all four failed on one shared type check rather than four separate gaps.
//
// The load-bearing assertions here are the ENCODING ones. A generated key that
// only this runtime can read is the classic failure for hand-built DER: it
// round-trips against itself perfectly and is worthless to every other
// implementation. So the tests below pin the exact PKCS#8/SPKI byte template
// against vectors produced by node v24.18.0, and check that deriving the public
// half from a NODE-generated private key reproduces node's own SPKI bytes.
//
// The GOLDEN_* keys were generated by node purely for this file. They protect
// nothing and are safe to commit.

type Spec = {
    type: 'x25519' | 'x448' | 'ed25519' | 'ed448';
    // First 16 bytes of the PKCS#8: SEQUENCE, version, AlgorithmIdentifier, and
    // the two OCTET STRING headers. Everything after this is the raw seed.
    prefix: string;
    pkcs8Length: number;
    spkiLength: number;
    goldenPrivateDer: string;
    goldenPublicDer: string;
};

const SPECS: readonly Spec[] = [
    {
        type: 'x25519',
        prefix: '302e020100300506032b656e04220420',
        pkcs8Length: 48,
        spkiLength: 44,
        goldenPrivateDer: '302e020100300506032b656e0422042048896ecca863b1c386cf8dbb6a907b6572f745e965d77af1ae843625e8f22845',
        goldenPublicDer: '302a300506032b656e0321003a5ce0cbfedcb2e962358f5c5630b65523c1beac687f7936bac14da943b4ae48',
    },
    {
        type: 'x448',
        prefix: '3046020100300506032b656f043a0438',
        pkcs8Length: 72,
        spkiLength: 68,
        goldenPrivateDer: '3046020100300506032b656f043a043818f471adb909a3be44bebc2daf447612640c10d1abd2b9c80200318674317b842e3f9a92ba77680364c98c7b39501bda293c153947003cc9',
        goldenPublicDer: '3042300506032b656f033900c4dd3830e9cc7ded0f7d131fe4d8fe2638b165169eda580713543d89dca4f6c9656644b0051be4f1a4cdc918d8bbf1276e2e21082507c46c',
    },
    {
        type: 'ed25519',
        prefix: '302e020100300506032b657004220420',
        pkcs8Length: 48,
        spkiLength: 44,
        goldenPrivateDer: '302e020100300506032b657004220420e1a08f79288c8670f15a3b89a5a8aadda75db2f58aa3bbaaa87514361955c929',
        goldenPublicDer: '302a300506032b657003210031a9b3166a007c052d3a1792b3927455dc5231cae06b2bac4a4d71e794ea8cc9',
    },
    {
        type: 'ed448',
        prefix: '3047020100300506032b6571043b0439',
        pkcs8Length: 73,
        spkiLength: 69,
        goldenPrivateDer: '3047020100300506032b6571043b0439b019e36b0d73c4ae37e281a21bc45849350a23ec8d77e8bb1a2c5269b837bbd61204c6589cb11f9a0e3bbd0125ea9499a1c3c6575b368e4a53',
        goldenPublicDer: '3043300506032b6571033a008c985be629aa8ed8e9d72185c96d23bbe3ab95d4fc8552063fab5cc5154e0bd174a6de0602e77949c0a6ec96158d39e56b4974ab3144fd6480',
    },
];

function privateDer(key: crypto.KeyObject): Buffer {
    return key.export({ type: 'pkcs8', format: 'der' }) as Buffer;
}

function publicDer(key: crypto.KeyObject): Buffer {
    return key.export({ type: 'spki', format: 'der' }) as Buffer;
}

Deno.test('crypto: generateKeyPairSync reports node\'s exact asymmetricKeyType for RFC 8410 types', () => {
    for (const { type } of SPECS) {
        const { publicKey, privateKey } = crypto.generateKeyPairSync(type);
        strictEqual(privateKey.asymmetricKeyType, type, `private ${type}`);
        strictEqual(publicKey.asymmetricKeyType, type, `public ${type}`);
        strictEqual(privateKey.type, 'private');
        strictEqual(publicKey.type, 'public');
        // Node reports an empty details object for these, not undefined.
        deepStrictEqual(privateKey.asymmetricKeyDetails, {});
    }
});

Deno.test('crypto: generated RFC 8410 PKCS#8 matches node\'s byte template exactly', () => {
    for (const { type, prefix, pkcs8Length, spkiLength } of SPECS) {
        const { publicKey, privateKey } = crypto.generateKeyPairSync(type);
        const priv = privateDer(privateKey);
        const pub = publicDer(publicKey);

        strictEqual(priv.byteLength, pkcs8Length, `${type} pkcs8 length`);
        strictEqual(pub.byteLength, spkiLength, `${type} spki length`);
        // Everything before the seed must be byte-identical to node's encoding;
        // a wrong OID or length byte here is exactly the non-interoperable
        // failure this test exists to catch.
        strictEqual(priv.subarray(0, 16).toString('hex'), prefix, `${type} pkcs8 prefix`);
    }
});

Deno.test('crypto: generated RFC 8410 keys round-trip through import', () => {
    for (const { type } of SPECS) {
        const { publicKey, privateKey } = crypto.generateKeyPairSync(type);

        const fromDer = crypto.createPrivateKey({ key: privateDer(privateKey), format: 'der', type: 'pkcs8' });
        strictEqual(fromDer.asymmetricKeyType, type, `${type} private der re-import`);

        const fromPem = crypto.createPrivateKey(privateKey.export({ type: 'pkcs8', format: 'pem' }) as string);
        strictEqual(fromPem.asymmetricKeyType, type, `${type} private pem re-import`);

        const pubFromDer = crypto.createPublicKey({ key: publicDer(publicKey), format: 'der', type: 'spki' });
        strictEqual(pubFromDer.asymmetricKeyType, type, `${type} public der re-import`);

        const pubFromPem = crypto.createPublicKey(publicKey.export({ type: 'spki', format: 'pem' }) as string);
        strictEqual(pubFromPem.asymmetricKeyType, type, `${type} public pem re-import`);

        // The public half returned by generation must be the one that actually
        // belongs to the private half, not merely a well-formed key.
        deepStrictEqual(publicDer(crypto.createPublicKey(privateKey)), publicDer(publicKey), `${type} derived public`);
    }
});

Deno.test('crypto: deriving from a node-generated RFC 8410 key reproduces node\'s SPKI bytes', () => {
    // Cross-implementation vector: node made both halves, so agreement here is
    // agreement with node's encoder, not with our own.
    for (const { type, goldenPrivateDer, goldenPublicDer } of SPECS) {
        const priv = crypto.createPrivateKey({
            key: Buffer.from(goldenPrivateDer, 'hex'),
            format: 'der',
            type: 'pkcs8',
        });
        strictEqual(priv.asymmetricKeyType, type, `${type} golden import`);
        strictEqual(privateDer(priv).toString('hex'), goldenPrivateDer, `${type} golden pkcs8 re-export`);
        strictEqual(publicDer(crypto.createPublicKey(priv)).toString('hex'), goldenPublicDer, `${type} golden spki derive`);
    }
});

Deno.test('crypto: RFC 8410 generation produces a fresh key each call', () => {
    for (const { type } of SPECS) {
        const first = privateDer(crypto.generateKeyPairSync(type).privateKey);
        const second = privateDer(crypto.generateKeyPairSync(type).privateKey);
        ok(!first.equals(second), `${type} generated the same key twice`);
    }
});

Deno.test('crypto: RFC 8410 generation ignores options, as node does', () => {
    for (const { type } of SPECS) {
        // No options argument at all, and options that mean nothing here: node
        // accepts both and ignores the contents.
        strictEqual(crypto.generateKeyPairSync(type).privateKey.asymmetricKeyType, type);
        const withJunk = crypto.generateKeyPairSync(type, { modulusLength: 2048, namedCurve: 'not-a-curve' });
        strictEqual(withJunk.privateKey.asymmetricKeyType, type, `${type} with junk options`);
    }
});

Deno.test('crypto: generateKeyPair async accepts both the 2-arg and 3-arg forms', async () => {
    for (const { type } of SPECS) {
        const twoArg = await new Promise<crypto.KeyObject>((resolve, reject) => {
            crypto.generateKeyPair(type, (err, _pub, priv) => (err ? reject(err) : resolve(priv as crypto.KeyObject)));
        });
        strictEqual(twoArg.asymmetricKeyType, type, `${type} 2-arg async`);

        const threeArg = await new Promise<crypto.KeyObject>((resolve, reject) => {
            crypto.generateKeyPair(type, {}, (err, _pub, priv) => (err ? reject(err) : resolve(priv as crypto.KeyObject)));
        });
        strictEqual(threeArg.asymmetricKeyType, type, `${type} 3-arg async`);
    }
});

Deno.test('crypto: key types this build cannot generate still report node\'s error', () => {
    // DSA and DH need parameter generation, which the native layer does not
    // expose; they must keep failing with node's message and code rather than
    // producing something unusable. Importing them already works, so do not
    // read this as "unsupported key type".
    for (const type of ['dsa', 'dh', 'bogus']) {
        throws(
            () => (crypto.generateKeyPairSync as (t: string, o?: unknown) => unknown)(type, { modulusLength: 1024 }),
            (err: Error & { code?: string }) => {
                strictEqual(err.message, `The argument 'type' must be a supported key type. Received '${type}'`);
                strictEqual(err.code, 'ERR_INVALID_ARG_VALUE');
                return true;
            },
            `${type} should be rejected`,
        );
    }
});
